version: '3'

services:
  
  # s3-media-svc:
  #   build: ./
  #   hostname: s3-media-svc
  #   restart: always
  #   env_file:
  #     - ./.env
  #   networks:
  #     - postgres
  #   depends_on:
  #     - postgres
  
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env
    networks:
      - postgres
  
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./.pgadmin.env
    networks:
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis

networks:
  postgres:
    driver: bridge
